---
- name: Print Inventory Variable
  hosts: arista5
  gather_facts: true
  vars_files: my_vars.yml
  tasks:
    - name: print arista5 ansible_facts
      debug:
        var: ansible_facts
    - name: print ipv4 addresses
      debug:
        var: net_all_ipv4_addresses
    - name: Print Network OS
      debug:
        var: ansible_network_os
    - name:
      debug:
        var: ansible_host
    - name: Print Group_Vars
      debug:
        var: desired_eos_version
    - name: Create a new variable 
      set_fact:
        device_hostname: "{{ inventory_hostname }}.lab.io"
    - name: print the new value
      debug: 
        var: device_hostname


