---
- name: Exercise 3c
  hosts: local
  gather_facts: False
  tasks:
    - debug:
        var: ansible_host

- name: Exercise 3c2
  hosts: cisco
  gather_facts: False
  tasks:
    - debug:
        var: ansible_connection

    - debug:
        var: ansible_host
