---
- name: Exercise 6a
  hosts: arista
  gather_facts: false
  tasks:
    - eos_command:
        commands: show ip arp
      register: output

    - debug:
        var: output

    - eos_command:
        commands: show ip arp | json
      register: output_jason

    - debug:
        var: output_jason
