---
- name: Exercise 3a
  hosts: nxos
  gather_facts: false
  tasks:
    - name: Gather Show version
      nxos_command:
        commands: "show version"
      register: output
    - name: Print output
      debug:
        var: output
