---
- name: verify VRF config
  hosts: cisco5:cisco6
  gather_facts: False
  tasks:
    - ios_command:
        commands:
          - "show ip vrf"
      register: output

    - debug:
        var: output.stdout_lines[0]
