---
- name: exercise 5
  hosts: juniper
  gather_facts: false
  tasks:
    - name: Juniper Comands
      junos_command:
        commands: show interfaces terse
      register: interfaces
    - name: Print Interfaces
      debug:
        msg: "Primary IP: {{ interfaces['stdout_lines'][0][-1] }}"
