---
- name: Exercise 3
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Change to Switchport
      nxos_interfaces:
        config:
          - name: "{{ interface }}"
            enabled: True
            mode: layer3
        state: merged

    - name: L3 Interface Configuration
      nxos_l3_interfaces:
        config:
          - name: "{{ interface }}"
            ipv4:
              - address: "{{ ip_address }}/{{ net_mask }}"
        state: merged

    - name: Ping
      net_ping:
        count: 5
        dest: "{{ peer_ip }}"
      register: output
      tags: pingtest

    - name: Verify PING
      assert:
        that:
          - output.packets_rx >= 4
      tags: pingtest

    - name: Verify RTT
      assert:
        that:
          - output.rtt.avg < 35
        fail_msg: "RTT is greater than 35"
        success_msg: "RTT is acceptable"
      tags: pingtest
              
