---
- name: Print Inventory Variable
  hosts: arista5
  gather_facts: false

  tasks:
    - name: Print Network OS
      debug:
        var: ansible_network_os
    - name:
      debug:
        var: ansible_host


