---
- name: exercise 5
  hosts: juniper
  gather_facts: false
  tasks:
    - name: Juniper Comands
      junos_command:
        commands: show interfaces terse
      register: interfaces
    - set_fact:
        int_line: "Primary IP: {{ interfaces['stdout_lines'][0][-1] }}"
    - debug:
        msg: "Primary IP: {{ int_line.split()[-1] }}"
