---
- name: Exercise 4
  hosts: arista
  gather_facts: False
  tasks:
    - name: Create VLAN
      eos_vlans:
        config:
          - name: "{{ vlan_name }}"
            vlan_id: "{{ vlan_number }}"
            state: active
    
    - name: Configure Switchport
      eos_l2_interfaces:
        config:
          - name: "{{ interface }}"
            access: 
              vlan: "{{ vlan_number }}"
        state: merged

    - name: Show Vlan
      eos_command:
        commands: show vlan | json
      register: output

    - set_fact:
        interfaces_dict: '{{ output.stdout[0].vlans["250"].interfaces }}'
        vlan_status: '{{ output.stdout[0].vlans["250"].status }}'

    - name: "Verify VLAN is active and {{ interface }} is assigned to VLAN"
      assert:
        that:
          - vlan_status == 'active'
          - "'Ethernet6' in interfaces_dict"


