---
- name: Exercise 4
  hosts: nxos
  gather_facts: false
  tasks:
    - name: Generate Interface Configuration
      template:
        src: interfaces.j2
        dest: "./CFGS/{{ inventory_hostname }}/{{ inventory_hostname }}-intf.txt"
    - name: Generate BGP Configuration
      template:
        src: bgp.j2
        dest: "./CFGS/{{ inventory_hostname }}/{{ inventory_hostname }}-bgp.txt"
    - name: Combine into single config file
      assemble:
        src: "./CFGS/{{ inventory_hostname }}/"
        dest: "./CFGS/{{ inventory_hostname }}-config.txt"

    - name: Deploy Configuration
      nxos_config:
        src: "./CFGS/{{ inventory_hostname }}-config.txt"

    - name: Verify BGP
      nxos_command:
        commands: "show ip bgp summary"
      register: output
      tags: bgp_verify

    - name: Display BGP neighbours
      debug:
        var: output.stdout_lines[0]
      tags: bgp_output
