---
- name: Exercise 1
  hosts: nxos
  gather_facts: false
  tasks:
    - name: Generate Interface Configuration
      template:
        src: interfaces.j2
        dest: "./CFGS/{{ inventory_hostname }}/{{ inventory_hostname }}-intf.txt"
    - name: Set BGP peer IP using hostvar
      set_fact:
        bgp_peer_ip: "{{ hostvars['nxos2']['eth1_4_ip_address'] }}" 
      when: "inventory_hostname == 'nxos1'"
    - name: Set BGP peer IP using hostvar
      set_fact:
        bgp_peer_ip: "{{ hostvars['nxos1']['eth1_4_ip_address'] }}"
      when: "inventory_hostname == 'nxos2'"
    - name: Generate BGP Configuration
      template:
        src: bgp.j2
        dest: "./CFGS/{{ inventory_hostname }}/{{ inventory_hostname }}-bgp.txt"
    - name: Combine into single config file
      assemble:
        src: "./CFGS/{{ inventory_hostname }}/"
        dest: "./CFGS/{{ inventory_hostname }}-config.txt"

    - name: Deploy Configuration
      nxos_config:
        src: "./CFGS/{{ inventory_hostname }}-config.txt"

    - name: Verify BGP
      nxos_command:
        commands: "show ip bgp summary"
      register: output
      tags: bgp_verify

    - name: Display BGP neighbours
      debug:
        var: output.stdout_lines[0]
      tags: bgp_output
