---
- name: Exercise 2
  hosts: nxos1
  gather_facts: false
  tasks: 
    - nxos_command:
        commands: "show vlan id {{ item }}"
      register: vlans
      loop:
        - 1
        - 2
        - 3
        - 4
    - debug:
        var: vlans["results"][3]["stdout_lines"]


