---
- name: Exercise 5
  hosts: cisco1:cisco2
  gather_facts: False
  tasks:
    - name: Run Show command
      ios_command:
        commands: show users
      register: output

    - name: Display output
      debug:
        var: output.stdout_lines[0]

    - name: Verifiy User
      assert: 
        that:
          - '"student1" in output.stdout[0]'
